version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: reviews
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6378:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--requirepass", "redis_password"]

volumes:
  mysql_data:
  redis_data:
